#!/bin/bash
# Auto-generated by WorkflowEngine — DO NOT EDIT
# Generated: 2026-03-15T23:57:50.628Z
# Workflow: "Default Workflow" (version 1)

# ─── Valid statuses (space-separated) ───
WORKFLOW_STATUSES="icebox planning backlog implementing review completed dev staging production"

# ─── Statuses that have a scopes/ subdirectory ───
WORKFLOW_DIR_STATUSES="icebox planning backlog implementing review completed dev staging production"

# ─── Terminal statuses ───
WORKFLOW_TERMINAL_STATUSES="completed dev staging production"

# ─── Entry point status ───
WORKFLOW_ENTRY_STATUS="icebox"

# ─── Transition edges (from:to:sessionKey) ───
WORKFLOW_EDGES=(
  "icebox:planning:"
  "planning:backlog:"
  "planning:implementing:implement"
  "backlog:implementing:implement"
  "implementing:review:reviewGate"
  "implementing:completed:"
  "review:completed:"
  "completed:dev:pushToDev"
  "dev:staging:pushToStaging"
  "staging:production:pushToProduction"
  "review:implementing:implement"
  "dev:implementing:implement"
  "completed:implementing:implement"
  "planning:icebox:"
  "backlog:planning:"
)

# ─── Branch-to-transition mapping (gitBranch:from:to:sessionKey) ───
WORKFLOW_BRANCH_MAP=(
  "staging:dev:staging:pushToStaging"
  "main:staging:production:pushToProduction"
)

# ─── Commit session branch patterns (regex) ───
WORKFLOW_COMMIT_BRANCHES="^(dev|feat/|fix/|scope/|chore/)"

# ─── Backward-compat direction aliases (alias:from:to:sessionKey) ───
WORKFLOW_DIRECTION_ALIASES=(
)

# ─── Helper functions ──────────────────────────────

status_to_dir() {
  local scope_status="$1"
  for s in $WORKFLOW_DIR_STATUSES; do
    [ "$s" = "$scope_status" ] && echo "$scope_status" && return 0
  done
  echo "$WORKFLOW_ENTRY_STATUS"
}

status_to_branch() {
  local status="$1"
  for entry in "${WORKFLOW_BRANCH_MAP[@]}"; do
    IFS=':' read -r branch from to skey <<< "$entry"
    [ "$to" = "$status" ] && echo "$branch" && return 0
  done
  echo ""
}

is_valid_status() {
  local status="$1"
  for s in $WORKFLOW_STATUSES; do
    [ "$s" = "$status" ] && return 0
  done
  return 1
}
