#!/bin/bash
# scope-helpers.sh — Shared utilities for scope lifecycle hooks
#
# Source this file from other scope hooks:
#   source "$(dirname "$0")/scope-helpers.sh"
set -e

# Check if a file path is a scope markdown file
is_scope_file() {
  local fp="$1"
  [[ "$fp" == *"scopes/"* && "$fp" == *.md ]]
}

SCOPE_PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
SCOPE_IMPLEMENTING_DIR="$SCOPE_PROJECT_DIR/scopes/implementing"

# ─── Source workflow manifest (auto-generated by WorkflowEngine) ───
MANIFEST_FILE="$SCOPE_PROJECT_DIR/.claude/config/workflow-manifest.sh"
if [ -f "$MANIFEST_FILE" ]; then
  source "$MANIFEST_FILE"
else
  # Fallback defaults (matches new Default trunk workflow)
  WORKFLOW_BRANCHING_MODE="trunk"
  WORKFLOW_STATUSES="icebox planning backlog implementing review completed main"
  WORKFLOW_DIR_STATUSES="icebox planning backlog implementing review completed main"
  WORKFLOW_ENTRY_STATUS="icebox"
  WORKFLOW_EDGES=(
    "planning:backlog:reviewScope"
    "backlog:implementing:implementScope"
    "implementing:review:reviewGate"
    "review:completed:commit"
    "completed:main:pushToMain"
  )
  WORKFLOW_BRANCH_MAP=(
    "main:completed:main:pushToMain"
  )
  WORKFLOW_COMMIT_BRANCHES="^(main|feat/|fix/|scope/|chore/)"
  WORKFLOW_DIRECTION_ALIASES=()
fi

# Ensure defaults for variables the manifest may not define
WORKFLOW_COMMIT_BRANCHES="${WORKFLOW_COMMIT_BRANCHES:-^(main|feat/|fix/|scope/|chore/)}"
if [ -z "${WORKFLOW_DIRECTION_ALIASES+x}" ]; then
  WORKFLOW_DIRECTION_ALIASES=()
fi

# Map status to directory name (manifest-driven)
status_to_dir() {
  local scope_status="$1"
  for s in $WORKFLOW_DIR_STATUSES; do
    [ "$s" = "$scope_status" ] && echo "$scope_status" && return 0
  done
  echo "$WORKFLOW_ENTRY_STATUS"
}

# Move a scope file to the directory matching target_status
move_scope() {
  local src="$1" target_status="$2"
  local dir_name=$(status_to_dir "$target_status")
  local target_dir="$SCOPE_PROJECT_DIR/scopes/$dir_name"
  local filename=$(basename "$src")
  mkdir -p "$target_dir"
  if ! git mv "$src" "$target_dir/$filename" 2>/dev/null; then
    echo "WARNING: git mv failed for $filename, using plain mv" >&2
    mv "$src" "$target_dir/$filename"
  fi
  echo "$target_dir/$filename"
}

# Find scopes with a given status in a specific directory
find_scopes_by_status() {
  local find_status="$1"
  local dir="${2:-$SCOPE_IMPLEMENTING_DIR}"
  [ -d "$dir" ] || return 1
  for f in "$dir"/*.md; do
    [ -f "$f" ] || continue
    head -15 "$f" | grep -q "^status: $find_status" && echo "$f"
  done
}

# Get the currently active scope (implementing > review > backlog > planning)
# Uses a session-scoped cache to avoid O(n) directory scans on every call.
# Call invalidate_active_scope_cache() after scope transitions.
find_active_scope() {
  local cache_file="$SCOPE_PROJECT_DIR/.claude/metrics/.active-scope"
  # Check cache: must exist, be < 60s old, and point to a real file
  if [ -f "$cache_file" ]; then
    local cached
    cached=$(cat "$cache_file" 2>/dev/null)
    if [ -n "$cached" ] && [ -f "$cached" ]; then
      local cache_age
      if [ "$(uname)" = "Darwin" ]; then
        cache_age=$(( $(date +%s) - $(stat -f %m "$cache_file") ))
      else
        cache_age=$(( $(date +%s) - $(stat -c %Y "$cache_file") ))
      fi
      if [ "$cache_age" -lt 60 ]; then
        echo "$cached"
        return 0
      fi
    fi
  fi

  # Cache miss — scan directories
  local scope
  scope=$(find_scopes_by_status "implementing" "$SCOPE_IMPLEMENTING_DIR" | head -1)
  [ -z "$scope" ] && scope=$(find_scopes_by_status "review" "$SCOPE_PROJECT_DIR/scopes/review" | head -1)
  [ -z "$scope" ] && scope=$(find_scopes_by_status "backlog" "$SCOPE_PROJECT_DIR/scopes/backlog" | head -1)
  [ -z "$scope" ] && scope=$(find_scopes_by_status "planning" "$SCOPE_PROJECT_DIR/scopes/planning" | head -1)

  if [ -n "$scope" ]; then
    mkdir -p "$(dirname "$cache_file")"
    printf '%s' "$scope" > "$cache_file"
    echo "$scope"
    return 0
  fi
  return 1
}

# Invalidate the active scope cache (call after transitions)
invalidate_active_scope_cache() {
  rm -f "$SCOPE_PROJECT_DIR/.claude/metrics/.active-scope"
}

# Get a YAML frontmatter field from a scope file
get_frontmatter() {
  local file="$1" field="$2"
  sed -n '2,/^---$/p' "$file" | grep "^$field:" | sed "s/^$field:[[:space:]]*//; s/^[\"']//; s/[\"']$//"
}

# Set a simple frontmatter field (top-level only, e.g. status, updated)
set_frontmatter() {
  local file="$1" field="$2" value="$3"
  local tmp="${file}.tmp.$$"
  (
    flock -x 200 2>/dev/null || true
    sed "s/^${field}:.*/${field}: ${value}/" "$file" > "$tmp" && mv "$tmp" "$file"
  ) 200>"${file}.lock"
  rm -f "${file}.lock"
}

# Append a UUID to a sessions array key in frontmatter
# Handles inline YAML arrays: key: [uuid1, uuid2]
append_session_uuid() {
  local file="$1" key="$2" uuid="$3"
  local tmp="${file}.tmp.$$"
  (
    flock -x 200 2>/dev/null || true
    awk -v key="$key" -v uuid="$uuid" '
      BEGIN { found_sessions=0; found_key=0; added=0 }
      /^sessions:/ {
        found_sessions=1
        if ($0 == "sessions: {}") {
          $0 = "sessions:"
          print
          print "  " key ": [" uuid "]"
          found_key=1; added=1
          next
        }
      }
      found_sessions && $0 ~ "^  " key ":" {
        found_key=1
        if (index($0, uuid) > 0) { added=1; print; next }
        # Append UUID to existing array: [a, b] -> [a, b, uuid]
        sub(/\]$/, ", " uuid "]")
        added=1
      }
      # After sessions: block ends (next top-level key), insert key if not found
      found_sessions && !found_key && /^[^ ]/ && !/^sessions:/ {
        print "  " key ": [" uuid "]"
        found_key=1; added=1
      }
      { print }
      END {
        # If sessions: block was never found, or key never added
        if (!found_sessions) {
          print "sessions:"
          print "  " key ": [" uuid "]"
        } else if (!added) {
          print "  " key ": [" uuid "]"
        }
      }
    ' "$file" > "$tmp" && mv "$tmp" "$file"
  ) 200>"${file}.lock"
  rm -f "${file}.lock"
}

# Find icebox file by slug (e.g. "onboarding-flow" matches scopes/icebox/onboarding-flow.md)
# or legacy scopes/icebox/502-onboarding-flow.md)
find_scope_by_slug() {
  local slug="$1"
  local icebox_dir="$SCOPE_PROJECT_DIR/scopes/icebox"
  [ -d "$icebox_dir" ] || return 1
  # Try slug-only file first
  if [ -f "$icebox_dir/${slug}.md" ]; then
    echo "$icebox_dir/${slug}.md"
    return 0
  fi
  # Fall back to legacy numeric-prefixed: {NNN}-{slug}.md
  for f in "$icebox_dir"/*-"${slug}.md"; do
    [ -f "$f" ] && echo "$f" && return 0
  done
  return 1
}

# Find scope file by numeric ID across all directories
find_scope_by_id() {
  local id="$1"
  local padded
  local id_clean
  id_clean=$(echo "$id" | sed 's/^0*//')
  [ -z "$id_clean" ] && id_clean="0"
  padded=$(printf '%03d' "$id_clean")
  find "$SCOPE_PROJECT_DIR/scopes/" -name "${padded}-*.md" -o -name "${padded}[a-dX]-*.md" 2>/dev/null | head -1
}
